### ISSUE TITLE
Just ship binary releases. Building Anki is endless pain.

### ISSUE THREAD

**Issue by ppd** [woodrow-shen/anki-snap#3]
Anki is a nightmare to build. Thus, I'm proposing shipping the binary releases from GitHub as is with minimal snapcraft sauce:

```yaml
name: anki-woodrow
base: core20 
version: "2.1.47"
summary: Anki is a friendly, intelligent spaced learning system.
description: |
  Anki is a program which makes remembering things easy. Because it's a lot
  more efficient than traditional study methods, you can either greatly
  decrease your time spent studying, or greatly increase the amount you learn.

grade: stable
confinement: strict
compression: lzo

apps:
  anki:
    command: usr/share/anki/bin/Anki
    desktop: usr/share/applications/anki.desktop
    plugs:
      - home
      - opengl
      - network
      - browser-support
      - audio-playback
      - audio-record
    environment:
      HOME: $SNAP_USER_COMMON
      QTWEBENGINE_DISABLE_SANDBOX: 1
    extensions:
      - gnome-3-38

parts:
  anki:
    plugin: nil
    source: https://github.com/ankitects/anki/releases/download/2.1.47/anki-2.1.47-linux.tar.bz2
    stage-packages:
      - libnss3
      - libxcb-icccm4
      - libxcb-image0
      - libxcb-keysyms1
      - libxcb-randr0
      - libxcb-render-util0
      - libxcb-shape0
      - libxcb-xinerama0
      - libxcb-xkb1
      - libxkbcommon-x11-0
    override-build: |
      export PREFIX="$SNAPCRAFT_PART_INSTALL/usr"
      echo "#!/bin/sh" > /usr/bin/xdg-mime && chmod +x /usr/bin/xdg-mime
      ./install.sh
      sed -i -e 's|Icon=anki|Icon=${SNAP}/usr/share/pixmaps/anki.png|g' \
        "$PREFIX/share/applications/anki.desktop"
```

This could be a sustainable way to maintain a KISS snap.
If you're feeling fancy, you could try to rip out the Qt libraries and use those from the `kde-neon` extension. But why bother. :man_shrugging: 

What do you think? Or are you not interested in maintaining the snap if you can't build from source?
